#define IN_USE		1
#define NOT_IN_USE	0

#define FEATURE_SET_ACTIVATION				NOT_IN_USE
#define FEATURE_FORCE_EXIT					IN_USE
#define FEATURE_USER_PERMISSION				NOT_IN_USE
#define FEATURE_CIFSD_SPAWN_ASYNC			NOT_IN_USE
#define FEATURE_CIFSD_CONF_WRITABLE			NOT_IN_USE
#define FEATURE_CLIENTD_ASYNC				NOT_IN_USE

#define USING(feature)		feature
